version: '3.9'
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 54358 --reload
    volumes:
      - .:/app
    ports:
      - "54358:54358"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  redis:
    image: "redis:alpine"